CREATE TABLE `orion_applicants`.`applicants` (
id        INT PRIMARY KEY AUTO_INCREMENT,
NAMECIRILIC VARCHAR(50),
NAMELATIN VARCHAR(50),
REGISTRATIONDATE Date,
VACANCY VARCHAR(50),
INVITATIONRECIEVED boolean,
DATEOFRECEIVINGINVITATION Date,
COMMENTARY VARCHAR(50),
CONTACT VARCHAR(50),
RECRUITER VARCHAR(50)
);